packages:
  - .
autoInstallPeers: true
configDependencies:
  "@savvy-web/pnpm-plugin-silk": 0.13.4+sha512-WNNQ5wNiBHfihbxFtX6oti+fxJb0AXHCVosdBCwFFyNXKk9YAWLM3Qa+9Z9b1x1bFedFBTsXjoDQk/kWAlddyg==
overrides:
  "@isaacs/brace-expansion": ^5.0.1
  "@savvy-web/github-action-effects": link:../github-action-effects/dist/npm
  lodash: ^4.17.23
  markdown-it: ^14.1.1
  minimatch: ">=10.2.3"
  smol-toml: ">=1.6.1"
  tmp: ^0.2.7
