import { existsSync, readFileSync } from "node:fs";
import { basename, join } from "node:path";
import {
	context,
	debug,
	endGroup,
	error,
	exec,
	getOctokit,
	getState,
	info,
	startGroup,
	warning,
} from "./_actions-compat.js";
import { createReleaseAssetAttestation } from "./create-attestation.js";
import type { TagInfo } from "./determine-tag-strategy.js";
import { findPackagePath } from "./find-package-path.js";
import type { PackagePublishResult, TargetPublishResult } from "./generate-publish-summary.js";
import { getPackagePageUrl } from "./generate-publish-summary.js";
import { getRegistryDisplayName } from "./registry-utils.js";

/**
 * Result of creating GitHub releases
 */
export interface CreateReleasesResult {
	/** Whether all releases were created successfully */
	success: boolean;
	/** Created releases */
	releases: ReleaseInfo[];
	/** Tags that were created */
	createdTags: string[];
	/** Errors encountered */
	errors: string[];
}

/**
 * Information about a created release
 */
export interface ReleaseInfo {
	/** Release tag name */
	tag: string;
	/** Release URL */
	url: string;
	/** Release ID */
	id: number;
	/** Uploaded assets */
	assets: AssetInfo[];
}

/**
 * Information about an uploaded asset
 */
export interface AssetInfo {
	/** Asset name */
	name: string;
	/** Download URL */
	downloadUrl: string;
	/** Asset size in bytes */
	size: number;
	/** Attestation URL if attestation was created */
	attestationUrl?: string | undefined;
	/** Registry this tarball was published to (if multi-target) */
	registry?: string | undefined;
}

/**
 * Extract release notes from CHANGELOG.md for a specific version
 *
 * @param changelogPath - Path to CHANGELOG.md
 * @param version - Version to extract notes for
 * @returns Release notes markdown or undefined
 */
function extractReleaseNotes(changelogPath: string, version: string): string | undefined {
	if (!existsSync(changelogPath)) {
		return undefined;
	}

	const content = readFileSync(changelogPath, "utf-8");
	const lines = content.split("\n");

	// Find the section for this version
	// Changesets format: ## 1.0.0 or ## @scope/pkg@1.0.0
	const versionPattern = new RegExp(`^##\\s+(?:@[^@]+@)?${version.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")}\\s*$`);
	const nextVersionPattern = /^##\s+/;

	let inSection = false;
	const sectionLines: string[] = [];

	for (const line of lines) {
		if (versionPattern.test(line)) {
			inSection = true;
			continue;
		}

		if (inSection) {
			if (nextVersionPattern.test(line)) {
				break;
			}
			sectionLines.push(line);
		}
	}

	if (sectionLines.length === 0) {
		return undefined;
	}

	// Trim leading/trailing empty lines
	while (sectionLines.length > 0 && sectionLines[0].trim() === "") {
		sectionLines.shift();
	}
	while (sectionLines.length > 0 && sectionLines[sectionLines.length - 1].trim() === "") {
		sectionLines.pop();
	}

	return sectionLines.join("\n");
}

/**
 * Get prefix for asset name from target directory
 *
 * Uses the last segment of the directory path (e.g., "dist/npm" -> "npm")
 *
 * @param directory - Target directory path
 * @returns Directory suffix for asset name prefix
 */
function getDirectoryPrefix(directory: string): string {
	const parts = directory.split("/").filter(Boolean);
	return parts[parts.length - 1] || "dist";
}

/**
 * Get the unscoped name from a package name
 *
 * @example
 * getUnscopedName("@savvy-web/rslib-builder") // returns "rslib-builder"
 * getUnscopedName("my-package") // returns "my-package"
 *
 * @param packageName - Full package name (may include scope)
 * @returns Unscoped package name
 */
function getUnscopedName(packageName: string): string {
	if (packageName.startsWith("@") && packageName.includes("/")) {
		return packageName.split("/")[1];
	}
	return packageName;
}

/**
 * Find API documentation file in a directory
 *
 * Looks for files matching the pattern `<unscopedPackageName>.api.json`
 * which are generated by API Extractor.
 *
 * @param directory - Directory to search in (may be undefined for targets without a directory)
 * @param packageName - Package name to derive the file name from
 * @returns Path to the API file if found, undefined otherwise
 */
function findApiDocFile(directory: string | undefined, packageName: string): string | undefined {
	if (!directory) {
		return undefined;
	}

	const unscopedName = getUnscopedName(packageName);
	const apiFileName = `${unscopedName}.api.json`;
	const apiFilePath = join(directory, apiFileName);

	if (existsSync(apiFilePath)) {
		debug(`Found API doc file: ${apiFilePath}`);
		return apiFilePath;
	}

	return undefined;
}

/**
 * Configure git identity for creating annotated tags
 *
 * @remarks
 * Annotated tags require a committer identity. This function configures
 * git user.name and user.email based on the GitHub App that created the token.
 */
async function configureGitIdentity(): Promise<void> {
	const appSlug = getState("appSlug");

	// Use app identity or fall back to github-actions bot
	const userName = appSlug ? `${appSlug}[bot]` : "github-actions[bot]";
	// Use a generic noreply email format - the exact ID doesn't matter for tag creation
	const userEmail = appSlug
		? `${appSlug}[bot]@users.noreply.github.com`
		: "41898282+github-actions[bot]@users.noreply.github.com";

	debug(`Configuring git identity: ${userName} <${userEmail}>`);

	await exec("git", ["config", "user.name", userName]);
	await exec("git", ["config", "user.email", userEmail]);
}

/**
 * Create a signed git tag via the GitHub API
 *
 * @remarks
 * Tags created via the GitHub API with a GitHub App token are automatically
 * verified/signed by GitHub, similar to commits created via the API.
 *
 * @param tagName - Name of the tag to create
 * @param message - Tag message
 * @param dryRun - Whether to skip actual tag creation
 * @returns Whether the tag was created successfully
 */
async function createGitTag(tagName: string, message: string, dryRun: boolean): Promise<boolean> {
	if (dryRun) {
		info(`[DRY RUN] Would create tag: ${tagName}`);
		return true;
	}

	const token = getState("token");
	if (!token) {
		error("No token available for creating signed tag");
		return false;
	}

	const octokit = getOctokit(token);
	const { owner, repo } = context.repo;

	try {
		// Get the current HEAD commit SHA
		let stdout = "";
		await exec("git", ["rev-parse", "HEAD"], {
			listeners: {
				stdout: (data: Buffer) => {
					stdout += data.toString();
				},
			},
			silent: true,
		});
		const headSha = stdout.trim();

		// Create an annotated tag object via the API (this makes it signed/verified)
		const { data: tagObject } = await octokit.rest.git.createTag({
			owner,
			repo,
			tag: tagName,
			message,
			object: headSha,
			type: "commit",
		});

		// Create a reference pointing to the tag object
		try {
			await octokit.rest.git.createRef({
				owner,
				repo,
				ref: `refs/tags/${tagName}`,
				sha: tagObject.sha,
			});
		} catch (refErr) {
			// On re-run the tag may already exist. Treat it as idempotent if
			// the existing ref resolves to the same commit; warn loudly only
			// when it points elsewhere (something genuinely diverged).
			const status = (refErr as { status?: number }).status;
			const refMessage = refErr instanceof Error ? refErr.message : String(refErr);
			if (status === 422 && /already exists/i.test(refMessage)) {
				try {
					const { data: existingRef } = await octokit.rest.git.getRef({
						owner,
						repo,
						ref: `tags/${tagName}`,
					});
					let existingCommitSha = existingRef.object.sha;
					if (existingRef.object.type === "tag") {
						const { data: existingTag } = await octokit.rest.git.getTag({
							owner,
							repo,
							tag_sha: existingRef.object.sha,
						});
						existingCommitSha = existingTag.object.sha;
					}
					if (existingCommitSha === headSha) {
						info(`Tag ${tagName} already exists at ${headSha} — treating as idempotent success`);
						return true;
					}
					warning(
						`Tag ${tagName} already exists but points to ${existingCommitSha}, not ${headSha} — skipping (manual review needed)`,
					);
					return false;
				} catch (lookupErr) {
					warning(
						`Tag ${tagName} reportedly already exists but lookup failed: ${lookupErr instanceof Error ? lookupErr.message : String(lookupErr)}`,
					);
					return false;
				}
			}
			throw refErr;
		}

		info(`Created and pushed tag: ${tagName}`);
		return true;
	} catch (err) {
		error(`Failed to create tag ${tagName}: ${err instanceof Error ? err.message : String(err)}`);
		return false;
	}
}

/**
 * Shape of the release object we keep around per tag — narrowed enough
 * to cover both the freshly-created and the looked-up paths without
 * dragging in Octokit's full response types.
 */
interface ResolvedRelease {
	readonly id: number;
	readonly htmlUrl: string;
}

/**
 * Asset descriptor used to short-circuit upload calls on re-run.
 */
interface ExistingAsset {
	readonly name: string;
	readonly browserDownloadUrl: string;
	readonly size: number;
}

/**
 * Upload an asset, but treat a name collision on re-run as a no-op —
 * the function returns the existing asset's URL so release notes and
 * `releaseInfo.assets` stay coherent.
 *
 * @remarks
 * GitHub returns 422 with `code: "already_exists"` when a release
 * already has an asset by the same name. Rather than delete-and-retry
 * (which risks racing with a concurrent run), we skip and reuse — the
 * user can delete the asset manually to force a re-upload.
 */
async function uploadAssetIdempotent(
	octokit: ReturnType<typeof getOctokit>,
	owner: string,
	repo: string,
	releaseId: number,
	fileName: string,
	fileContent: Buffer,
	existingAssets: Map<string, ExistingAsset>,
): Promise<ExistingAsset> {
	const cached = existingAssets.get(fileName);
	if (cached) {
		info(`Asset ${fileName} already attached to release — skipping upload`);
		return cached;
	}
	try {
		const asset = await octokit.rest.repos.uploadReleaseAsset({
			owner,
			repo,
			release_id: releaseId,
			name: fileName,
			data: fileContent as unknown as string,
		});
		const result: ExistingAsset = {
			name: fileName,
			browserDownloadUrl: asset.data.browser_download_url,
			size: asset.data.size,
		};
		existingAssets.set(fileName, result);
		return result;
	} catch (err) {
		const status = (err as { status?: number }).status;
		if (status === 422 && /already_exists/i.test(err instanceof Error ? err.message : String(err))) {
			// A concurrent run beat us to it. Fall back to a fresh list-assets
			// fetch so we can hand back the same shape as the success path.
			const { data: assets } = await octokit.rest.repos.listReleaseAssets({
				owner,
				repo,
				release_id: releaseId,
				per_page: 100,
			});
			const found = assets.find((a) => a.name === fileName);
			if (found) {
				const result: ExistingAsset = {
					name: fileName,
					browserDownloadUrl: found.browser_download_url,
					size: found.size,
				};
				existingAssets.set(fileName, result);
				info(`Asset ${fileName} already attached (raced) — using existing copy`);
				return result;
			}
		}
		throw err;
	}
}

/**
 * Create GitHub releases for published packages
 *
 * @remarks
 * This function:
 * 1. Creates git tags for each release
 * 2. Creates GitHub releases with release notes from CHANGELOG
 * 3. Uploads package artifacts to each release
 *
 * @param tags - Tags to create releases for
 * @param publishResults - Results from publishing packages
 * @param packageManager - Package manager to use (npm, pnpm, yarn, bun)
 * @param dryRun - Whether to skip actual creation
 * @returns Promise resolving to release creation result
 */
export async function createGitHubReleases(
	tags: TagInfo[],
	publishResults: PackagePublishResult[],
	_packageManager: string,
	dryRun: boolean,
): Promise<CreateReleasesResult> {
	const token = getState("token");
	if (!token) {
		throw new Error("No token available from state - ensure pre.ts ran successfully");
	}
	const octokit = getOctokit(token);

	const releases: ReleaseInfo[] = [];
	const createdTags: string[] = [];
	const errors: string[] = [];

	startGroup("Creating GitHub releases");

	// Configure git identity for creating annotated tags (required for non-dry-run)
	if (!dryRun) {
		await configureGitIdentity();
	}

	for (const tag of tags) {
		info(`Processing release for ${tag.name}...`);

		// Find packages associated with this tag
		const associatedPackages = publishResults.filter((pkg) => {
			if (tag.packageName.includes(", ")) {
				// Fixed versioning - multiple packages
				return tag.packageName.includes(pkg.name);
			}
			return pkg.name === tag.packageName;
		});

		if (associatedPackages.length === 0) {
			warning(`No packages found for tag ${tag.name}`);
			continue;
		}

		// Build release notes
		let releaseNotes = "";

		for (const pkg of associatedPackages) {
			// Try to find CHANGELOG in the package directory via workspaces-effect-backed lookup
			const pkgPath = findPackagePath(pkg.name);
			const changelogPaths: string[] = [];

			if (pkgPath) {
				changelogPaths.push(join(pkgPath, "CHANGELOG.md"));
			}
			// Fall back to root changelog for single-package repos
			changelogPaths.push(join(process.cwd(), "CHANGELOG.md"));

			let notes: string | undefined;
			for (const changelogPath of changelogPaths) {
				debug(`Looking for CHANGELOG at: ${changelogPath}`);
				notes = extractReleaseNotes(changelogPath, pkg.version);
				if (notes) {
					debug(`Found release notes for ${pkg.name}@${pkg.version} in ${changelogPath}`);
					break;
				}
			}

			if (associatedPackages.length > 1) {
				releaseNotes += `## ${pkg.name}\n\n`;
			}
			releaseNotes += notes || `Released version ${pkg.version}`;
			releaseNotes += "\n\n";
		}

		// Build publish summary table
		// Collect all successful targets with their info
		const publishedTargets: Array<{
			pkg: PackagePublishResult;
			target: TargetPublishResult;
			registryName: string;
			packageUrl: string | undefined;
		}> = [];

		for (const pkg of associatedPackages) {
			for (const target of pkg.targets.filter((t) => t.success)) {
				const registryName = getRegistryDisplayName(target.target.registry);
				const packageUrl = getPackagePageUrl(target.target.registry ?? null, pkg.name, pkg.version);
				publishedTargets.push({ pkg, target, registryName, packageUrl });
			}
		}

		if (publishedTargets.length === 0) {
			releaseNotes += "> This is a version-only release. No packages were published to a registry.\n\n";
		}

		if (publishedTargets.length > 0) {
			releaseNotes += "---\n\n";
			releaseNotes += "### Publish Summary\n\n";
			releaseNotes += "| Registry | Package | SBOM | API | Provenance |\n";
			releaseNotes += "|----------|---------|------|-----|------------|\n";

			for (const { pkg, target, registryName, packageUrl } of publishedTargets) {
				const packageCell = packageUrl ? `[${pkg.name}@${pkg.version}](${packageUrl})` : `${pkg.name}@${pkg.version}`;

				// SBOM cell - will be updated after assets are uploaded
				const sbomCell = target.sbomPath ? "📦" : "—";

				// API doc cell - will be updated after assets are uploaded
				const apiDocExists = findApiDocFile(target.target.directory, pkg.name) !== undefined;
				const apiCell = apiDocExists ? "📄" : "—";

				// Provenance cell - combine npm provenance and GitHub attestation
				const provenanceParts: string[] = [];
				if (target.attestationUrl) {
					provenanceParts.push(`[Sigstore](${target.attestationUrl})`);
				}
				if (pkg.githubAttestationUrl) {
					provenanceParts.push(`[GitHub](${pkg.githubAttestationUrl})`);
				}
				if (target.sbomAttestationUrl) {
					provenanceParts.push(`[SBOM](${target.sbomAttestationUrl})`);
				}
				const provenanceCell = provenanceParts.length > 0 ? provenanceParts.join(", ") : "—";

				releaseNotes += `| ${registryName} | ${packageCell} | ${sbomCell} | ${apiCell} | ${provenanceCell} |\n`;
			}
		}

		// Create git tag
		const tagMessage = `Release ${tag.name}`;
		const tagCreated = await createGitTag(tag.name, tagMessage, dryRun);

		if (!tagCreated && !dryRun) {
			errors.push(`Failed to create tag ${tag.name}`);
			continue;
		}

		createdTags.push(tag.name);

		// Create GitHub release
		if (dryRun) {
			info(`[DRY RUN] Would create GitHub release for ${tag.name}`);
			releases.push({
				tag: tag.name,
				url: `https://github.com/${context.repo.owner}/${context.repo.repo}/releases/tag/${tag.name}`,
				id: 0,
				assets: [],
			});
			continue;
		}

		try {
			// Resolve the release for this tag. On re-run GitHub returns 422
			// with `already_exists` — in that case we fetch the existing
			// release and proceed, so the asset-upload loop can refresh any
			// missing files instead of failing the whole job.
			let release: ResolvedRelease;
			try {
				const created = await octokit.rest.repos.createRelease({
					owner: context.repo.owner,
					repo: context.repo.repo,
					tag_name: tag.name,
					name: tag.name,
					body: releaseNotes.trim(),
					draft: false,
					prerelease: tag.version.includes("-"),
				});
				release = { id: created.data.id, htmlUrl: created.data.html_url };
				info(`Created release: ${release.htmlUrl}`);
			} catch (createErr) {
				const status = (createErr as { status?: number }).status;
				const createMessage = createErr instanceof Error ? createErr.message : String(createErr);
				if (status === 422 && /already_exists|already exists/i.test(createMessage)) {
					const existing = await octokit.rest.repos.getReleaseByTag({
						owner: context.repo.owner,
						repo: context.repo.repo,
						tag: tag.name,
					});
					release = { id: existing.data.id, htmlUrl: existing.data.html_url };
					info(`Release for ${tag.name} already exists — reusing: ${release.htmlUrl}`);
				} else {
					throw createErr;
				}
			}

			// Pre-fetch existing assets so the helper can skip name collisions
			// without an extra round-trip per upload.
			const existingAssetsByName = new Map<string, ExistingAsset>();
			try {
				const { data: assets } = await octokit.rest.repos.listReleaseAssets({
					owner: context.repo.owner,
					repo: context.repo.repo,
					release_id: release.id,
					per_page: 100,
				});
				for (const a of assets) {
					existingAssetsByName.set(a.name, {
						name: a.name,
						browserDownloadUrl: a.browser_download_url,
						size: a.size,
					});
				}
			} catch (listErr) {
				warning(
					`Failed to enumerate existing assets for ${tag.name}: ${listErr instanceof Error ? listErr.message : String(listErr)}`,
				);
			}

			const releaseInfo: ReleaseInfo = {
				tag: tag.name,
				url: release.htmlUrl,
				id: release.id,
				assets: [],
			};

			// Upload artifacts for each package using tarball paths from publish results
			for (const pkg of associatedPackages) {
				// Collect successful targets with tarball paths
				const targetsWithTarballs = pkg.targets.filter((t) => t.success && t.tarballPath);

				if (targetsWithTarballs.length === 0) {
					// Don't fall back to packing from the package's source
					// directory — that tarball would include source files
					// (test/, build cache, configs) that aren't part of the
					// published artifact, so any attestation against it
					// would describe a different bundle than what's on the
					// registry. The publish path always packs from
					// target.directory (which honors publishConfig.targets),
					// so a missing tarballPath here means the publish step
					// itself didn't produce one — skip with a warning.
					warning(`No tarball path recorded for ${pkg.name}@${pkg.version} — skipping release-asset upload`);
					continue;
				}

				// Check if we have multiple unique directories (multi-target with different content)
				const uniqueDirectories = new Set(targetsWithTarballs.map((t) => t.target.directory));
				const needsPrefix = uniqueDirectories.size > 1;

				// Track uploaded paths to avoid duplicates (same tarball for multiple targets)
				const uploadedPaths = new Set<string>();

				// Track SBOM URLs for release notes update
				const sbomAssetUrls = new Map<string, string>();

				// Track API doc URLs for release notes update
				const apiDocAssetUrls = new Map<string, string>();

				for (const targetResult of targetsWithTarballs) {
					const artifactPath = targetResult.tarballPath;
					if (!artifactPath) continue; // Type guard (already filtered but TS doesn't know)

					// Skip if already uploaded (same tarball used for multiple targets sharing directory)
					if (uploadedPaths.has(artifactPath)) continue;
					uploadedPaths.add(artifactPath);

					try {
						const originalFileName = basename(artifactPath);
						// Prefix with directory name if multiple directories (e.g., "npm-my-package-1.0.0.tgz")
						const fileName = needsPrefix
							? `${getDirectoryPrefix(targetResult.target.directory)}-${originalFileName}`
							: originalFileName;

						const fileContent = readFileSync(artifactPath);

						info(`Uploading asset: ${fileName}${needsPrefix ? ` (from ${targetResult.target.directory})` : ""}`);

						const asset = await uploadAssetIdempotent(
							octokit,
							context.repo.owner,
							context.repo.repo,
							release.id,
							fileName,
							fileContent,
							existingAssetsByName,
						);

						info(`Uploaded: ${asset.browserDownloadUrl}`);

						const attestationResult = await createReleaseAssetAttestation(artifactPath, pkg.name, pkg.version, dryRun);

						releaseInfo.assets.push({
							name: fileName,
							downloadUrl: asset.browserDownloadUrl,
							size: asset.size,
							attestationUrl: attestationResult.success ? attestationResult.attestationUrl : undefined,
							registry: targetResult.target.registry ?? undefined,
						});

						if (attestationResult.success && attestationResult.attestationUrl) {
							info(`  ✓ Created attestation: ${attestationResult.attestationUrl}`);
						}

						// Upload SBOM if available
						if (targetResult.sbomPath && existsSync(targetResult.sbomPath)) {
							try {
								const sbomFileName = basename(targetResult.sbomPath);
								const sbomContent = readFileSync(targetResult.sbomPath);

								info(`Uploading SBOM: ${sbomFileName}`);

								const sbomAsset = await uploadAssetIdempotent(
									octokit,
									context.repo.owner,
									context.repo.repo,
									release.id,
									sbomFileName,
									sbomContent,
									existingAssetsByName,
								);

								info(`Uploaded SBOM: ${sbomAsset.browserDownloadUrl}`);

								// Track SBOM URL for release notes
								sbomAssetUrls.set(targetResult.target.directory, sbomAsset.browserDownloadUrl);

								releaseInfo.assets.push({
									name: sbomFileName,
									downloadUrl: sbomAsset.browserDownloadUrl,
									size: sbomAsset.size,
								});
							} catch (sbomErr) {
								warning(
									`Failed to upload SBOM ${targetResult.sbomPath}: ${sbomErr instanceof Error ? sbomErr.message : String(sbomErr)}`,
								);
							}
						}

						// Upload API documentation file if available
						const apiDocPath = findApiDocFile(targetResult.target.directory, pkg.name);
						if (apiDocPath) {
							try {
								const apiDocFileName = basename(apiDocPath);
								// Prefix with directory name if multiple targets
								const finalApiDocFileName = needsPrefix
									? `${getDirectoryPrefix(targetResult.target.directory)}-${apiDocFileName}`
									: apiDocFileName;
								const apiDocContent = readFileSync(apiDocPath);

								info(`Uploading API doc: ${finalApiDocFileName}`);

								const apiDocAsset = await uploadAssetIdempotent(
									octokit,
									context.repo.owner,
									context.repo.repo,
									release.id,
									finalApiDocFileName,
									apiDocContent,
									existingAssetsByName,
								);

								info(`Uploaded API doc: ${apiDocAsset.browserDownloadUrl}`);

								// Track API doc URL for release notes
								apiDocAssetUrls.set(targetResult.target.directory, apiDocAsset.browserDownloadUrl);

								releaseInfo.assets.push({
									name: finalApiDocFileName,
									downloadUrl: apiDocAsset.browserDownloadUrl,
									size: apiDocAsset.size,
								});
							} catch (apiDocErr) {
								warning(
									`Failed to upload API doc ${apiDocPath}: ${apiDocErr instanceof Error ? apiDocErr.message : String(apiDocErr)}`,
								);
							}
						}
					} catch (err) {
						warning(`Failed to upload artifact ${artifactPath}: ${err instanceof Error ? err.message : String(err)}`);
					}
				}

				// Update release notes with SBOM links
				if (sbomAssetUrls.size > 0) {
					// Replace the placeholder SBOM cells with actual links
					for (const [_dir, sbomUrl] of sbomAssetUrls) {
						// Update release notes to replace "📦" with actual link for this target
						releaseNotes = releaseNotes.replace(
							/\| 📦 \| (📄|—) \| (\[Sigstore\]|\[GitHub\]|\[SBOM\]|—)/,
							`| [📦](${sbomUrl}) | $1 | $2`,
						);
					}
				}

				// Update release notes with API doc links
				if (apiDocAssetUrls.size > 0) {
					// Replace the placeholder API doc cells with actual links
					for (const [_dir, apiDocUrl] of apiDocAssetUrls) {
						// Update release notes to replace "📄" with actual link for this target
						releaseNotes = releaseNotes.replace(
							/\| 📄 \| (\[Sigstore\]|\[GitHub\]|\[SBOM\]|—)/,
							`| [📄](${apiDocUrl}) | $1`,
						);
					}
				}
			}

			// Update the release body with SBOM links
			if (releaseInfo.assets.length > 0) {
				try {
					await octokit.rest.repos.updateRelease({
						owner: context.repo.owner,
						repo: context.repo.repo,
						release_id: release.id,
						body: releaseNotes.trim(),
					});
					info(`Updated release notes with asset links`);
				} catch (err) {
					warning(`Failed to update release notes: ${err instanceof Error ? err.message : String(err)}`);
				}
			}

			releases.push(releaseInfo);
		} catch (err) {
			const errorMessage = `Failed to create release for ${tag.name}: ${err instanceof Error ? err.message : String(err)}`;
			error(errorMessage);
			errors.push(errorMessage);
		}
	}

	endGroup();

	return {
		success: errors.length === 0,
		releases,
		createdTags,
		errors,
	};
}
