/**
 * Tests for the generated release-PR description.
 *
 * The behaviour that matters is narrow and easy to lose: **GitHub links an
 * issue when the PR body carries a bare `Closes #N` line outside any fenced
 * block.** Everything else in the body is presentation.
 *
 * Verified against the live repository before these were written:
 * `savvy-web/silk-integration` #242 and #232 were created with an empty body
 * and reported `closingIssuesReferences: []`; #243 carried a bare `Closes #168`
 * and reported `[168]`.
 */

import { describe, expect, it } from "vitest";
import type { LinkedIssueRef } from "../src/utils/pr-body.js";
import {
	MANAGED_END,
	MANAGED_START,
	REFERENCES_END,
	REFERENCES_START,
	REFERENCES_START_PREFIX,
	SQUASH_FENCE_LANGUAGE,
	SUMMARY_END,
	SUMMARY_START,
	buildClosingReferences,
	buildManagedPrBody,
	buildSquashClosingReferences,
	extractReferences,
	extractSummary,
	upsertManagedRegion,
} from "../src/utils/pr-body.js";

const SIGNOFF = "Signed-off-by: C. Spencer Beggs <spencer@savvyweb.systems>";

const openIssue = (number: number, title = "Some title"): LinkedIssueRef => ({ number, title, state: "open" });
const closedIssue = (number: number, title = "Done already"): LinkedIssueRef => ({ number, title, state: "closed" });

const body = (linkedIssues: ReadonlyArray<LinkedIssueRef>): string =>
	buildManagedPrBody({
		subject: "release: 2.0.0",
		linkedIssues,
		signoff: SIGNOFF,
		summary: "",
	});

/**
 * Strip every fenced code block.
 *
 * @remarks
 * This is the whole point of the suite: a `Closes #N` **inside** a fence is
 * inert to GitHub's linker. Asserting on the raw body would pass on the
 * proposed-squash-commit block alone and prove nothing.
 */
const outsideFences = (markdown: string): string => markdown.replace(/```[\s\S]*?```/g, "");

describe("buildManagedPrBody — what it deliberately omits", () => {
	it("carries no boilerplate preamble", () => {
		const rendered = body([openIssue(168)]);

		// The title, branch and author already say this.
		expect(rendered).not.toContain("Release PR");
		expect(rendered).not.toContain("automatically generated by the release workflow");
	});

	it("carries no file-level version listing", () => {
		const rendered = body([openIssue(168)]);

		// A `git status` dump — two lines per package — says nothing the release
		// table does not say better, on the same page.
		expect(rendered).not.toContain("Version Changes");
		expect(rendered).not.toContain("pkgs/dependency/package.json");
	});
});

describe("buildManagedPrBody — the linking contract", () => {
	it("emits a bare `Closes #N` line OUTSIDE any fenced block", () => {
		const plain = outsideFences(body([openIssue(168)]));
		expect(plain.split("\n").map((l) => l.trim())).toContain("Closes #168");
	});

	it("emits one bare closing line per open issue", () => {
		const plain = outsideFences(body([openIssue(1), openIssue(2), openIssue(3)]));
		const lines = plain.split("\n").map((l) => l.trim());
		expect(lines).toContain("Closes #1");
		expect(lines).toContain("Closes #2");
		expect(lines).toContain("Closes #3");
	});

	it("does NOT emit a closing reference for an already-closed issue", () => {
		const plain = outsideFences(body([openIssue(10), closedIssue(11)]));
		const lines = plain.split("\n").map((l) => l.trim());
		expect(lines).toContain("Closes #10");
		expect(lines).not.toContain("Closes #11");
		// And nowhere else either: the human-readable list is gone, so a closed
		// issue leaves no trace rather than a struck-through one.
		expect(body([openIssue(10), closedIssue(11)])).not.toContain("#11");
	});

	it("produces no closing references when nothing is linked", () => {
		expect(buildClosingReferences([])).toBe("");
		expect(outsideFences(body([]))).not.toContain("Closes #");
	});
});

describe("buildManagedPrBody — the proposed squash-commit block", () => {
	it("fences the block with the `proposed-squash-commit` language", () => {
		expect(body([openIssue(168)])).toContain("```proposed-squash-commit");
		// Pinned as a constant so a well-meaning "fix" to `text` fails here.
		expect(SQUASH_FENCE_LANGUAGE).toBe("proposed-squash-commit");
	});

	it("carries the subject, the closing reference and the resolved signoff", () => {
		const fenced = /```proposed-squash-commit\n([\s\S]*?)```/.exec(body([openIssue(168)]))?.[1] ?? "";
		expect(fenced).toContain("release: 2.0.0");
		expect(fenced).toContain("Closes #168");
		expect(fenced).toContain(SIGNOFF);
	});

	it("takes the signoff from its argument rather than hard-coding an identity", () => {
		const other = buildManagedPrBody({
			subject: "release: 1.0.0",
			linkedIssues: [openIssue(5)],
			signoff: "Signed-off-by: Someone Else <other@example.com>",
			summary: "",
		});
		expect(other).toContain("Signed-off-by: Someone Else <other@example.com>");
		expect(other).not.toContain("savvyweb.systems");
	});
});

describe("upsertManagedRegion", () => {
	it("preserves human content written above the managed region", () => {
		const human = "Some notes I typed by hand.\n\nAnd a second paragraph.";
		const first = upsertManagedRegion(human, body([openIssue(168)]));
		expect(first).toContain("Some notes I typed by hand.");
		expect(first).toContain("And a second paragraph.");
		expect(first).toContain(MANAGED_START);
	});

	it("replaces a previous managed region rather than appending a second one", () => {
		const first = upsertManagedRegion("", body([openIssue(168)]));
		const second = upsertManagedRegion(first, body([openIssue(200)]));

		expect(second.split(MANAGED_START)).toHaveLength(2);
		expect(second.split(MANAGED_END)).toHaveLength(2);
		const plain = outsideFences(second)
			.split("\n")
			.map((l) => l.trim());
		expect(plain).toContain("Closes #200");
		expect(plain).not.toContain("Closes #168");
	});

	it("keeps human content when the region is regenerated", () => {
		const human = "Reviewer note: hold until Friday.";
		const first = upsertManagedRegion(human, body([openIssue(168)]));
		const second = upsertManagedRegion(first, body([openIssue(168), openIssue(169)]));
		expect(second).toContain("Reviewer note: hold until Friday.");
		expect(
			outsideFences(second)
				.split("\n")
				.map((l) => l.trim()),
		).toContain("Closes #169");
	});

	it("seeds an empty body with just the managed region", () => {
		const seeded = upsertManagedRegion("", body([openIssue(168)]));
		expect(seeded.startsWith(MANAGED_START)).toBe(true);
		expect(seeded.trimEnd().endsWith(MANAGED_END)).toBe(true);
	});
});

describe("the two Closes spellings", () => {
	it("comma-joins inside the squash block and one-per-line outside it", () => {
		const rendered = body([openIssue(170), openIssue(171)]);
		const fenced = /```proposed-squash-commit\n([\s\S]*?)```/.exec(rendered)?.[1] ?? "";
		const plain = outsideFences(rendered)
			.split("\n")
			.map((l) => l.trim());

		// commitlint reads one comma-joined trailer…
		expect(fenced).toContain("Closes #170, #171");
		expect(fenced).not.toContain("Closes #170\nCloses #171");
		// …GitHub's linker reads one bare reference per line. Neither accepts the
		// other's spelling, which is why both are emitted.
		expect(plain).toContain("Closes #170");
		expect(plain).toContain("Closes #171");
		expect(plain).not.toContain("Closes #170, #171");
	});

	it("emits no squash trailer when nothing is linked", () => {
		expect(buildSquashClosingReferences([])).toBe("");
	});

	it("omits a closed issue from the comma-joined form too", () => {
		expect(buildSquashClosingReferences([openIssue(1), closedIssue(2)])).toBe("Closes #1");
	});
});

describe("the AI summary region", () => {
	it("reserves the region even when empty, and puts it first", () => {
		const rendered = body([openIssue(170)]);

		expect(rendered).toContain(SUMMARY_START);
		expect(rendered).toContain(SUMMARY_END);
		// Nothing of ours may sit above it — a reader meets the prose first.
		expect(rendered.indexOf(SUMMARY_START)).toBeLessThan(rendered.indexOf("proposed-squash-commit"));
	});

	it("carries an existing summary through a regeneration", () => {
		// The destructive case: the managed region is rebuilt on every run, so a
		// summariser's work must survive the next release commit.
		const withSummary = buildManagedPrBody({
			subject: "release: 2.0.0",
			linkedIssues: [openIssue(170)],
			signoff: SIGNOFF,
			summary: "This release fixes the widget.",
		});

		expect(extractSummary(withSummary)).toBe("This release fixes the widget.");
		expect(withSummary).toContain("This release fixes the widget.");
	});

	it("reads back nothing from a body that has no region", () => {
		expect(extractSummary("just some prose")).toBe("");
	});

	it("reads back nothing from an empty region", () => {
		expect(extractSummary(body([openIssue(170)]))).toBe("");
	});
});

describe("the closing-reference region", () => {
	it("delimits the bare references with markers, keeping them outside the fence", () => {
		const rendered = body([openIssue(168)]);

		// The action emits the attributed opening form, not the plain constant.
		expect(rendered).toContain(REFERENCES_START_PREFIX);
		expect(rendered).toContain(REFERENCES_END);
		// The markers must not push the references inside a fence — that would
		// make them inert to GitHub's linker, which is the whole point of them.
		expect(
			outsideFences(rendered)
				.split("\n")
				.map((l) => l.trim()),
		).toContain("Closes #168");
	});

	it("reserves the region even when nothing is linked", () => {
		// An empty region is still an addressable one. A release with nothing
		// linked is exactly when an agent most wants somewhere to write.
		const rendered = body([]);
		expect(rendered).toContain(REFERENCES_START_PREFIX);
		expect(rendered).toContain(REFERENCES_END);
		expect(extractReferences(rendered)).toBe("");
	});

	it("reads back its own references", () => {
		expect(extractReferences(body([openIssue(1), openIssue(2)]))).toBe("Closes #1\nCloses #2");
	});

	it("reads back nothing from a body that has no region", () => {
		expect(extractReferences("just some prose")).toBe("");
	});

	it("carries through a reference for an issue this run does not know about", () => {
		// The destructive case the markers exist to prevent: an agent links an
		// issue the release never detected, and the next push rebuilds the region
		// from `linkedIssues` alone and deletes it silently.
		const withAgentEdit = buildManagedPrBody({
			subject: "release: 2.0.0",
			linkedIssues: [openIssue(170)],
			signoff: SIGNOFF,
			summary: "",
			priorBody: `${REFERENCES_START}\nCloses #999\n${REFERENCES_END}`,
		});

		const plain = outsideFences(withAgentEdit)
			.split("\n")
			.map((l) => l.trim());
		expect(plain).toContain("Closes #170");
		expect(plain).toContain("Closes #999");
	});

	it("does not resurrect an issue this run deliberately dropped as closed", () => {
		// The action decides every issue it knows about. A stale carried line
		// must not re-link an issue that has since been closed.
		const rendered = buildManagedPrBody({
			subject: "release: 2.0.0",
			linkedIssues: [openIssue(10), closedIssue(11)],
			signoff: SIGNOFF,
			summary: "",
			priorBody: `<!-- silk-release:references:start owned="10,11" -->\nCloses #10\nCloses #11\n${REFERENCES_END}`,
		});

		expect(rendered).not.toContain("#11");
	});

	it("does not duplicate a carried reference it already emits", () => {
		const rendered = buildManagedPrBody({
			subject: "release: 2.0.0",
			linkedIssues: [openIssue(170)],
			signoff: SIGNOFF,
			summary: "",
			priorBody: `${REFERENCES_START}\nCloses #170\nCloses #170\n${REFERENCES_END}`,
		});

		// Scoped to the region: the squash block legitimately carries its own
		// copy, so counting across the whole body proves nothing.
		expect(extractReferences(rendered).match(/Closes #170/g)).toHaveLength(1);
	});

	it("ignores a number that no closing keyword governs", () => {
		const rendered = buildManagedPrBody({
			subject: "release: 2.0.0",
			linkedIssues: [],
			signoff: SIGNOFF,
			summary: "",
			priorBody: `${REFERENCES_START}\nSee also #500\nRelated to #501\n${REFERENCES_END}`,
		});

		expect(rendered).not.toContain("#500");
		expect(rendered).not.toContain("#501");
	});

	it("survives a full regeneration round-trip through the managed region", () => {
		const first = upsertManagedRegion(
			"",
			buildManagedPrBody({
				subject: "release: 1.0.0",
				linkedIssues: [openIssue(170)],
				signoff: SIGNOFF,
				summary: "",
				priorBody: `${REFERENCES_START}\nCloses #999\n${REFERENCES_END}`,
			}),
		);

		const second = upsertManagedRegion(
			first,
			buildManagedPrBody({
				subject: "release: 2.0.0",
				linkedIssues: [openIssue(171)],
				signoff: SIGNOFF,
				summary: extractSummary(first),
				priorBody: first,
			}),
		);

		const plain = outsideFences(second)
			.split("\n")
			.map((l) => l.trim());
		// This run's own reference, and the agent's addition still standing.
		expect(plain).toContain("Closes #171");
		expect(plain).toContain("Closes #999");
		// #170 belonged to the previous run and is no longer linked.
		expect(plain).not.toContain("Closes #170");
	});
});

describe("what the body no longer carries", () => {
	it("has no run attribution", () => {
		// GitHub already shows the run in the checks.
		expect(body([openIssue(170)])).not.toContain("Generated with");
	});

	it("has no human-readable issue list", () => {
		// It duplicated the closing references directly below it.
		const rendered = body([openIssue(170)]);
		expect(rendered).not.toContain("Linked Issues");
	});
});
